from __future__ import annotations

from typing import Protocol, Optional


class BrowserClientPort(Protocol):
    def goto(self, url: str, timeout_ms: Optional[int] = None) -> None: ...
    def click(self, selector: str, timeout_ms: Optional[int] = None) -> None: ...
    def fill(self, selector: str, value: str, timeout_ms: Optional[int] = None) -> None: ...
    def select(self, selector: str, value: str, timeout_ms: Optional[int] = None) -> None: ...
    def wait_for_selector(self, selector: str, timeout_ms: Optional[int] = None) -> None: ...
    def wait_for_url(self, url: str, timeout_ms: Optional[int] = None) -> None: ...
    def text(self, selector: str) -> str: ...
    def attr(self, selector: str, attr: str) -> str: ...
    def screenshot(self, path: Optional[str] = None) -> str: ...
    def close(self) -> None: ...
